### ISSUE TITLE
Convert the Authenticated Orion Match Functions to C# Library

### ISSUE THREAD

**Issue by erikkanderson** [shooterstech/BabelFish#2]

**Comment by adam-shooterstech** [comment]
Looking at test integrating of AWS4RequestSigner to generate signature for authenticated call
https://github.com/tsibelman/aws-signer-v4-dot-net
https://www.nuget.org/packages/Aws4RequestSigner/

**Comment by erikkanderson** [comment]
Fixed in a previous issue.
