### ISSUE TITLE
Add DeviceToken logic to initial Cognito auth to complete Authentication effort

### ISSUE THREAD

**Issue by adam-shooterstech** [shooterstech/BabelFish#21]
Finish adding logic for DeviceToken authResponse ChallengeName on initial login to Cognito.

**Comment by reweiser3** [comment]
closing; using the newer version of BabelFish; the user and identity manager's have been modified to use CognitoUser instead of the Microsoft Idenetity base user system. Temporary keys are stored in the results schema to be modify the user's claims to include the user's security tokens from Cognit

**Comment by reweiser3** [comment]
closing; using the newer version of BabelFish; the user and identity manager's have been modified to use CognitoUser instead of the Microsoft Idenetity base user system. Temporary keys are stored in the results schema to be modify the user's claims to include the user's security tokens from Cognito
